theme = "hugo-devresume-theme"
relativeURLs = true
baseURL = "/"
title = "Fabrice Gabolde's portfolio"

[params]
author = "Fabrice Gabolde"
description = "Fabrice Gabolde's portfolio static website"
primaryColor = "#54B689"
textPrimaryColor = "#292929"

[params.profile]
enable = true
name = "Fabrice Gabolde"
tagline = "Senior Software Engineer"
avatar = "avatar.jpeg"

[params.contact]
enable = true
location = "Paris, France"

[[params.contact.list]]
icon = "fas fa-phone-square"
url = "tel:#"
text = "+33 6 07 61 18 61"
[[params.contact.list]]
icon = "fas fa-envelope-square"
url = "mailto:#"
text = "fabrice.gabolde@gmail.com"
[[params.contact.list]]
icon = "fas fa-globe"
url = "#"
text = "portfolio.pokki.net"


[params.skills]
enable = true

[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "Java 11 to 21"
[[params.skills.list.items]]
details = "Perl, Clojure, some Python"
[[params.skills.list.items]]
details = "RDBMS (MySQL/MariaDB, Postgres); Snowflake"
[[params.skills.list.items]]
details = "Redis, Elasticsearch"
[[params.skills.list.items]]
details = "OpenAPI, Terraform, Git, GitLab"
[[params.skills.list.items]]
details = "Kubernetes, Helm, Docker"
[[params.skills.list.items]]
details = "HTTP API design"
[[params.skills.list.items]]
details = "Relational database schemas that make sense and perform "
[[params.skills.list.items]]
details = "Complex but maintainable software systems"

[[params.skills.list]]
title = "Professional"
[[params.skills.list.items]]
details = "Effective communication"
[[params.skills.list.items]]
details = "Team player"
[[params.skills.list.items]]
details = "Strong problem solver"
[[params.skills.list.items]]
details = "Good time management"

[params.education]
enable = true

[[params.education.list]]
degree = "Engineering Degree in Computer Science"
university = "Institut National des Sciences Appliquées de Lyon"
dates = "2005 - 2010"
[[params.education.list]]
degree = "MSc in Computer Science"
university = "Université Claude Bernard Lyon 1"
dates = "2009 - 2010"

[params.awards]
enable = false

[[params.awards.list]]
name = "Award Lorem Ipsum"
body = "Microsoft lorem ipsum"
date = "2019"
[[params.awards.list]]
name = "Award Donec Sodales"
body = "Oracle Aenean"
date = "2017"

[params.languages]
enable = true

[[params.languages.list]]
name = "French"
level = "Native"
[[params.languages.list]]
name = "English"
level = "Professional"
[[params.languages.list]]
name = "Spanish"
level = "Conversational"

[params.interests]
enable = true

[[params.interests.list]]
name = "Table-top role playing games"
[[params.interests.list]]
name = "Reading"

[params.summary]
enable = true
text = "I'm a primarily Java developer who thrives when building foundations for the rest of the team. I love creating tooling, improving DX, ensuring that other engineers have an experience as painless as possible. Along the way, I've somehow gotten pretty good at designing HTTP APIs, RESTful or not.\n\nI enjoy a variety of styles of programming languages: imperative (Java, Perl) or functional (Clojure), object-oriented or not. I know when to use design patterns and when to avoid them. Enough DevOps skills to competently shoot myself in the foot. _Strong_ opinions on Hibernate.\n\nThis resume is entirely LLM-free."

[params.experience]
enable = true

[[params.experience.list]]
title = "Senior Software Engineer"
dates = "2019 - Present"
company = "Weborama"
details = "Lead developer for a team of 3 other backend API developers, working in close cooperation with the frontend team, backend processing team, and SRE. In addition, led CI and Observability tooling, developer support and evangelism for the Java software development teams of Weborama."
[[params.experience.list.items]]
details = "Led the transition for multiple applications from relying on several legacy in-house authentication systems to a unified SSO experience with OIDC using Keycloak."
[[params.experience.list.items]]
details = "Designed the architecture of Snowflake customer data silos and built a database analysis tool with the goal of making customer data stes available and discoverable within other Weborama products."
[[params.experience.list.items]]
details = "Designed a modular architecture for pluggable applications on the aforementioned system, keeping the focus on security by design and separation of concerns."

[[params.experience.list]]
title = "Software Engineer"
dates = "2014 - 2019"
company = "Weborama"
details = "Design and implementation for a large refactor of an existing application to use Java 17/21 and Spring Boot 3 instead of Perl 5.12."
[[params.experience.list.items]]
details = "Designed and built several features for human-guided generation of word clouds from a large corpus of web content, to help in scoring user profiles along user-built topics."
[[params.experience.list.items]]
details = "Participated in the transition from behavioral-based user profiling (cookies) to contextual-based (no cookies) and back again (depending on the Google Chrome team's mood of the day)."
[[params.experience.list.items]]
details = "Advocated for using OpenAPI to describe HTTP APIs instead of older, low-adoption systems like [SPORE](https://spore.github.io/), or manually written and unmaintained documentation, and built much of the company tooling for taking advantage of it."
[[params.experience.list.items]]
details = "Participated in the design of a big data pipeline for building user profiles for advertising: large scale web crawling with built-in rate-limiting, following robots.txt, and analyzing the page text using decluttering heuristics and OpenNLP."

[[params.experience.list]]
title = "Software Developer"
dates = "2011 - 2014"
company = "Devoteam SA"
details = "Part of the Uperto open-source team at Devoteam, with a focus on Perl and network monitoring technologies."
[[params.experience.list.items]]
details = "Implemented and helped design a system for automatically encrypting emails containing sensitive medical information for the French Social Security IT systems. (Perl, SMTP/LMTP, GPG, Postfix, Debian)"
[[params.experience.list.items]]
details = "Implemented a large French telco operator's migration from telnet-based edge router monitoring to using SNMP, as part of their network monitoring overhaul. (Perl, SNMP, Zabbix 2, Debian)"
[[params.experience.list.items]]
details = "Refactored and maintained a Perl and Oracle based tool for generating reporting data for monitoring SLAs for a large French bank. (Perl, Oracle 10, Solaris)"

[params.projects]
enable = false

[[params.projects.list]]
title = "Project Lorem Ipsum"
meta = "Open Source"
tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

[[params.projects.list]]
title = "Project Sed Fringilla"
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[[params.projects.list]]
title = "Project Praesent"
meta = "Open Source"
tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[params.information]
enable = false

[[params.information.list]]
title = "Papers"
[[params.information.list.items]]
details = "2018 · Lorem Ipsum"
[[params.information.list.items]]
details = "2016 · Sed Fringilla"

[[params.information.list]]
title = "Interests"
details = "Climbing, Snowboarding, Photography, Travelling"

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/fgabolde"
title = "fgabolde"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/fgabolde"
title = "fgabolde"
[[params.social.list]]
icon = "fas fa-user"
url = "//bsky.app/profile/pokki.net"
title = "@pokki.net on Bluesky"
